Repository kubernetes-client/python, pull requests merged in 2018-10, with the labels that each got.

#635 Generate 8.0.0a1 client on release-8.0 branch
  kubernetes/README.md
  kubernetes/__init__.py
  kubernetes/client/api_client.py
  kubernetes/client/configuration.py
  scripts/constants.py
  setup.py
Labels: approved, cncf-cla: yes, lgtm, size/S

#647 Add link to kubernetes-client slack channel to README
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#667 change pep8 into pycodestyle since pep8 is depreciated
  .travis.yml
  scripts/update-pycodestyle.sh
  test-requirements.txt
  tox.ini
Labels: approved, cncf-cla: yes, lgtm, size/S

#665 Update Travis CI to use most current k8s server version
  .travis.yml
  scripts/kube-init.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#446 Add example for remote cluster without kube client on server
  examples/remote_cluster.py
Labels: approved, cncf-cla: yes, lgtm, size/M
