Repository kubernetes-client/python, pull requests merged in 2019-06, with the labels that each got.

#816 Fix broken dependencies.
  requirements.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS

#782 Add method to dynamically set namespace in yaml files
  kubernetes/e2e_test/test_utils.py
  kubernetes/utils/create_from_yaml.py
Labels: approved, cncf-cla: yes, lgtm, size/M

#856 Don't use latest stable version for minikube
  scripts/kube-init.sh
Labels: approved, cncf-cla: yes, lgtm, size/S
