Repository kubernetes-client/python, pull requests merged in 2019-08, with the labels that each got.

#786 feat: add Job examples
  examples/job_examples.py
  examples/pi-job.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#893 Docs update
  .gitignore
  doc/Makefile
  doc/README.md
  doc/requirements-docs.txt
  doc/source/conf.py
  doc/source/contributing.rst
  doc/source/index.rst
  doc/source/readme.rst
  setup.py
  test-requirements.txt
Labels: approved, cncf-cla: yes, lgtm, size/M

#915 Move inactive members to emeritus
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#918 Temporary pin minikube to 1.2.0 due to regression in 1.3.0
  scripts/kube-init.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#916 Add issue templates
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/feature.md
Labels: approved, cncf-cla: yes, lgtm, size/M, tide/merge-method-squash

#929 Restore latest release of minikube
  scripts/kube-init.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#922 Update examples
  doc/source/index.rst
  doc/source/usage.rst
  examples/create_deployment.py
  examples/create_deployment_from_yaml.py
  examples/deployment_examples.py
Labels: approved, cncf-cla: yes, lgtm, size/M, tide/merge-method-squash

#933 Added Ingress Example
  examples/ingress-example.py
Labels: approved, cncf-cla: yes, lgtm, size/L

#924 Update support matrix
  README.md
  RELEASE.md
Labels: approved, cncf-cla: yes, lgtm, size/M
