Repository kubernetes-client/python, pull requests merged in 2019-10, with the labels that each got.

#975 Update py.test to pytest
  tox.ini
Labels: approved, cncf-cla: yes, lgtm, size/S

#978 Port coverage report generation to pytest
  test-requirements.txt
  tox.ini
Labels: approved, cncf-cla: yes, lgtm, size/XS

#970 Enable testing for Python 3.8
  .travis.yml
  setup.py
  tox.ini
Labels: approved, cncf-cla: yes, lgtm, size/M
