Repository kubernetes-client/python, pull requests merged in 2019-07, with the labels that each got.

#807 Drop Python3.4
  .travis.yml
  tox.ini
Labels: approved, cncf-cla: yes, lgtm, size/XS

#883 #877: Remove reference to incubator
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#873 kube-init.sh: die is not a command
  scripts/kube-init.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#887 Fix custom object patch API content type in release-10.0 branch
  CHANGELOG.md
  kubernetes/client/apis/custom_objects_api.py
Labels: approved, cncf-cla: yes, kind/bug, lgtm, priority/critical-urgent, size/S

#889 Update docs python version for Travis CI
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#795 Allow creation from dict
  kubernetes/e2e_test/test_utils.py
  kubernetes/e2e_test/test_yaml/apps-deployment-2.yaml
  kubernetes/utils/__init__.py
  kubernetes/utils/create_from_yaml.py
Labels: approved, cncf-cla: yes, lgtm, size/L

#824 Fix AttributeError in create_from_yaml
  kubernetes/e2e_test/test_utils.py
  kubernetes/utils/create_from_yaml.py
Labels: approved, cncf-cla: yes, lgtm, size/S

#732 feat: remove dependency on mvn from updating script
  scripts/update-client.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#846 Enhancements for example3.py and example4.py
  examples/example3.py
  examples/example4.py
Labels: approved, cncf-cla: yes, lgtm, size/XS

#894 Python 3.4 is no longer supported
  setup.py
Labels: approved, cncf-cla: yes, lgtm, size/XS

#897 Update urllib3 for CVE-2019-11324
  requirements.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS

#848 add example of using custom resources
  examples/create_thirdparty_resource.md
  examples/custom_object.py
Labels: approved, cncf-cla: yes, lgtm, size/L

#896 Travis CI: The sudo: tag is now fully deprecated in Travis
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#907 Add micw523 to reviewers
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#888 Deprecate extensions/v1beta1 deployment
  examples/create_deployment.py
  examples/create_deployment_from_yaml.py
  examples/deployment_examples.py
  examples/nginx-deployment.yaml
  examples/notebooks/create_deployment.ipynb
  examples/notebooks/intro_notebook.ipynb
  kubernetes/e2e_test/test_utils.py
  kubernetes/e2e_test/test_yaml/dep-deployment.yaml
  kubernetes/e2e_test/test_yaml/extensions-deployment.yaml
  kubernetes/e2e_test/test_yaml/list.yaml
  kubernetes/e2e_test/test_yaml/triple-nginx.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L
