Repository kubernetes-client/python, pull requests merged in 2019-11, with the labels that each got.

#865 Update README.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1011 fix: add client.api package to setup.py
  setup.py
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1014 Generate 11.0.0b2 client
  CHANGELOG.md
  README.md
  kubernetes/README.md
  kubernetes/__init__.py
  kubernetes/client/__init__.py
  kubernetes/client/api_client.py
  kubernetes/client/configuration.py
  scripts/constants.py
  setup.py
Labels: approved, cncf-cla: yes, lgtm, size/M

#1015 Update README and CHANGELOG in master branch
  CHANGELOG.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S
