Repository kubernetes-client/python, pull requests merged in 2019-04, with the labels that each got.

#797 Long term solution for using minikube in CI
  scripts/kube-init.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#767 Add Rbac support for creating from YAML
  kubernetes/e2e_test/test_utils.py
  kubernetes/e2e_test/test_yaml/rbac-role.yaml
  kubernetes/utils/create_from_yaml.py
Labels: approved, cncf-cla: yes, lgtm, size/S

#805 Re-generate client for 10.0.0a1 release
  kubernetes/README.md
  kubernetes/__init__.py
  kubernetes/client/api_client.py
  kubernetes/client/configuration.py
  scripts/constants.py
  setup.py
Labels: approved, cncf-cla: yes, lgtm, size/S

#820 Correct inconsistent spacing and typos
  CONTRIBUTING.md
  OWNERS
  README.md
  devel/release.md
  devel/stats.md
  devel/submodules.md
Labels: approved, cncf-cla: yes, lgtm, size/M
