Repository kubernetes-client/python, pull requests merged in 2020-09, with the labels that each got.

#1252 remove duplicate lines from kubernetes/README.md
  kubernetes/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1254 Update the CHANGELOG and README
  CHANGELOG.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#1259 Add dependabot.
  .github/dependabot.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1229 Update Release Doc
  RELEASE.md
  devel/release.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#1262 Returns the created k8s objects in create_from_{dict,yaml}.
  kubernetes/utils/create_from_yaml.py
Labels: approved, cncf-cla: yes, lgtm, size/S
