Repository kubernetes-client/python, pull requests merged in 2020-03, with the labels that each got.

#1087 add basic watch configmap e2e test
  kubernetes/e2e_test/test_watch.py
Labels: approved, cncf-cla: yes, lgtm, size/M

#1096 Add kubernetes.dynamic to setup.py pkg list
  setup.py
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1099 Support travis pypi deployment
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1100 Redo pypi token encryption for travis ci deployment
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1101 Travis configuration now does extra tag validation
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1102 Fix verify_tag build stage in Travis pipeline
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1106 Improve compatibility-matrix documentation in alignment with client-go
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#1109 Automated cherry pick of #1099 #1100 #1101 #1102
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1111 Update CHANGELOG with a missed bug fix
  CHANGELOG.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1108 Automated cherry pick of #1099 #1100 #1101 #1102
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1104 Cherry-pick CHANGELOG and README from release 11.0 branch
  CHANGELOG.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#1120 Run spell check tools to fix typos:
  devel/release.md
  kubernetes/utils/quantity.py
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1126 fix: e2e tests with conntrack required by k8s/minikube
  scripts/kube-init.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1103 Update the hotfix patch list and add a script to automate the patching process
  devel/release.md
  scripts/apply-hotfixes.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#1113 Cherry pick v10.1.0 changelog from #1091
  CHANGELOG.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
