Repository kubernetes-client/python, pull requests merged in 2020-02, with the labels that each got.

#1073 Cleanup ThreadPool with atexit rather than __del__
  kubernetes/client/api_client.py
  kubernetes/test/test_api_client.py
Labels: approved, cncf-cla: yes, lgtm, size/M

#1076 Document hot issues in release process
  devel/release.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#1077 cherry-pick of #1073 to release-12.0: Fix python3 hang
  kubernetes/client/api_client.py
  kubernetes/test/test_api_client.py
Labels: approved, cncf-cla: yes, lgtm, size/M

#1078 cherry-pick of #1073 to release-11.0: Fix python3 hang
  kubernetes/client/api_client.py
  kubernetes/test/test_api_client.py
Labels: approved, cncf-cla: yes, lgtm, size/M

#1038 Grammar fixes to contributing doc
  CONTRIBUTING.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#1083 Add example code for enabling debugging
  examples/deployment_crud.py
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1051 Update README and CHANGELOG for 11.0.0 stable release
  CHANGELOG.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#1079 cherry-pick of #1073 to release-10.0: Fix python3 hang
  examples/create_deployment.py
  examples/create_deployment_from_yaml.py
  examples/deployment_examples.py
  examples/nginx-deployment.yaml
  examples/notebooks/create_deployment.ipynb
  examples/notebooks/intro_notebook.ipynb
  kubernetes/client/api_client.py
  kubernetes/e2e_test/test_apps.py
  kubernetes/e2e_test/test_utils.py
  kubernetes/e2e_test/test_yaml/apps-deployment.yaml
  kubernetes/e2e_test/test_yaml/dep-deployment.yaml
  kubernetes/e2e_test/test_yaml/extensions-deployment.yaml
  kubernetes/e2e_test/test_yaml/list.yaml
  kubernetes/e2e_test/test_yaml/multi-resource-with-list.yaml
  kubernetes/e2e_test/test_yaml/triple-nginx.yaml
  kubernetes/test/test_api_client.py
  requirements.txt
Labels: approved, cncf-cla: yes, lgtm, size/L

#1090 Update CHANGELOG to include 10.0.1
  CHANGELOG.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
