Repository kubernetes-client/python, pull requests merged in 2020-11, with the labels that each got.

#1309 Update hot patch section of release documentation
  devel/release.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1308 Update CHANGELOG and README to reflect v12.0.0 and v12.0.1
  CHANGELOG.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#1321 Update support and compatibitility sections of documentation
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#1323 [v17] Cherry-pick: Update to the compatibility and support sections in README
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#1324 [v12] Cherry-pick: Update to the compatibility and support sections in README
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#1329 Implement back end raw port test container using python.
  kubernetes/e2e_test/port_server.py
  kubernetes/e2e_test/test_client.py
Labels: approved, cncf-cla: yes, lgtm, size/L

#1311 Add Python 3.9 to build
  .github/workflows/test.yaml
  .travis.yml
  setup.py
  tox.ini
Labels: approved, cncf-cla: yes, lgtm, size/S
