Repository kubernetes-client/python, pull requests merged in 2021-12, with the labels that each got.

#1644 Automated release of 21.7.0b1 upstream release 21.0 1638829098
  .github/workflows/e2e-master.yaml
  .github/workflows/e2e-release-11.0.yaml
  .github/workflows/e2e-release-12.0.yaml
  .github/workflows/e2e-release-17.0.yaml
  .github/workflows/e2e-release-18.0.yaml
  .github/workflows/test.yaml
  CHANGELOG.md
  README.md
  kubernetes/README.md
  kubernetes/__init__.py
  kubernetes/client/__init__.py
  kubernetes/client/api_client.py
  kubernetes/client/configuration.py
  scripts/constants.py
  setup.py
Labels: kind/bug, lgtm, cncf-cla: yes, size/M, approved, release-note-none

#1645 update README and change log for 21.7.0b1
  CHANGELOG.md
  README.md
Labels: lgtm, cncf-cla: yes, size/XS, kind/documentation, approved, release-note-none

#1650 test: WSClient.returncode idempotence
  kubernetes/e2e_test/test_client.py
Labels: lgtm, cncf-cla: yes, size/XS, release-note, approved, needs-kind

#1653 Automated release of 21.7.0 upstream release 21.0 1639590783
  CHANGELOG.md
  README.md
  kubernetes/README.md
  kubernetes/__init__.py
  kubernetes/client/__init__.py
  kubernetes/client/api_client.py
  kubernetes/client/configuration.py
  kubernetes/e2e_test/test_client.py
  scripts/constants.py
  setup.py
Labels: kind/bug, lgtm, cncf-cla: yes, size/M, approved, release-note-none

#1654 cherrypick CHANGELOG and README
  CHANGELOG.md
  README.md
Labels: lgtm, cncf-cla: yes, size/XS, kind/documentation, approved, release-note-none

#1657 Misc typo fixes
  README.md
  examples/deployment_crud.py
  examples/dynamic-client/namespaced_custom_resource.py
  examples/job_crud.py
  examples/notebooks/create_secret.ipynb
  examples/notebooks/intro_notebook.ipynb
  scripts/apply-hotfixes.sh
Labels: lgtm, cncf-cla: yes, size/S, kind/documentation, approved, release-note-none

#1664 Fix typos discovered by codespell
  CHANGELOG.md
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/cleanup, release-note-none
