Repository kubernetes-client/python, pull requests merged in 2021-11, with the labels that each got.

#1592 Update readme in release-19.0 branch
  README.md
Labels: lgtm, cncf-cla: yes, size/XS, kind/documentation, approved, release-note-none

#1619 Automated release of 20.12.0b1 upstream release 20.0 1636397891
  CHANGELOG.md
  README.md
  kubernetes/README.md
  kubernetes/__init__.py
  kubernetes/client/__init__.py
  kubernetes/client/api_client.py
  kubernetes/client/configuration.py
  scripts/constants.py
  setup.py
Labels: kind/bug, lgtm, cncf-cla: yes, size/S, approved, release-note-none

#1620 1.20 beta release updates
  CHANGELOG.md
  README.md
Labels: kind/bug, lgtm, cncf-cla: yes, size/S, approved, release-note-none

#1621 Update README.md SSL version check syntax
  README.md
Labels: lgtm, cncf-cla: yes, size/XS, kind/documentation, approved, release-note-none

#1628 Automated release of 20.13.0 upstream release 20.0 1637343269
  .github/workflows/e2e-master.yaml
  .github/workflows/e2e-release-11.0.yaml
  .github/workflows/e2e-release-12.0.yaml
  .github/workflows/e2e-release-17.0.yaml
  .github/workflows/e2e-release-18.0.yaml
  .github/workflows/test.yaml
  CHANGELOG.md
  README.md
  kubernetes/README.md
  kubernetes/__init__.py
  kubernetes/client/__init__.py
  kubernetes/client/api_client.py
  kubernetes/client/configuration.py
  scripts/constants.py
  setup.py
Labels: kind/bug, lgtm, cncf-cla: yes, size/M, approved, release-note-none

#1629 v1.20 GA release: update CHANGELOG and README
  CHANGELOG.md
  README.md
Labels: lgtm, cncf-cla: yes, size/S, kind/documentation, approved, release-note-none

#1638 Use v1 API in the ingress example
  examples/ingress_create.py
Labels: lgtm, cncf-cla: yes, approved

#1639 Automated release of 21.7.0a1 upstream release 21.0 1638232914
  CHANGELOG.md
  README.md
  kubernetes/README.md
  kubernetes/__init__.py
  kubernetes/client/__init__.py
  kubernetes/client/api_client.py
  kubernetes/client/configuration.py
  scripts/constants.py
  setup.py
Labels: kind/bug, lgtm, cncf-cla: yes, size/S, approved, release-note-none

#1640 update README and changelog from 21.7.0a1
  CHANGELOG.md
  README.md
Labels: lgtm, cncf-cla: yes, size/XS, kind/documentation, approved, release-note-none

#1631 Fix leaderelection.resourcelock not found
  setup.py
Labels: kind/bug, lgtm, cncf-cla: yes, size/XS, approved, release-note-none
