Repository kubernetes-client/python, pull requests merged in 2021-04, with the labels that each got.

#1419 add update-submodule script
  .github/PULL_REQUEST_TEMPLATE.md
  devel/submodules.md
  scripts/update-submodule.sh
  scripts/util/changelog.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#1322 Cherry-pick: Update CHANGELOG with v17.14.0a1
  CHANGELOG.md
Labels: approved, cncf-cla: yes, lgtm, needs-kind, size/XS

#1425 Fix release notes for v18.17.0a1 and v17.14.0a1 in release-18.0 branch
  CHANGELOG.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/M

#1431 configure the openapi-generator version
  scripts/update-client.sh
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#1433 Fix CustomResourceDefinition manifest yaml in custom_object.py example
  examples/custom_object.py
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/S

#1435 simplify & enhance the node_labels.py example
  examples/node_labels.py
Labels: approved, cncf-cla: yes, kind/cleanup, kind/documentation, lgtm, release-note-none, size/S

#1437 Add example to demonstrate usage of `patch_cluster_custom_object` method
  examples/cluster_scoped_custom_object.py
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/L

#1441 Detect OS X sed and fail client generation script
  scripts/update-client.sh
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/S

#1443 Apply-hotfixes: use commits from upstream repo instead of a forked repo
  scripts/apply-hotfixes.sh
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#1440 Removed custom_object.py and created a new file namespaced_custom_object.py which is more specific to usage of namespaced custom resource
  examples/namespaced_custom_object.py
Labels: approved, cncf-cla: yes, kind/cleanup, kind/documentation, lgtm, release-note-none, size/S

#1442 examples: comment improvement in remote_cluster.py and deployment_cre…
  examples/deployment_create.py
  examples/remote_cluster.py
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/S
