Repository kubernetes-client/python, pull requests merged in 2021-05, with the labels that each got.

#1450 add example to demonstrate a rolling restart of the deployment
  examples/dynamic-client/deployment_rolling_restart.py
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/L

#1451 Update CHANGELOG and README in master branch
  CHANGELOG.md
  README.md
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/M

#1454 add 'list_ingressroute_for_all_namespaces' method
  examples/dynamic-client/namespaced_custom_resource.py
Labels: approved, cncf-cla: yes, kind/cleanup, kind/documentation, lgtm, release-note-none, size/M

#1457 Refactor OS X sed check into a util
  scripts/update-client.sh
  scripts/update-submodule.sh
  scripts/util/common.sh
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/M

#1464 Release 17.17.0
  CHANGELOG.md
  README.md
  kubernetes/README.md
  kubernetes/__init__.py
  kubernetes/client/__init__.py
  kubernetes/client/api_client.py
  kubernetes/client/configuration.py
  scripts/constants.py
  setup.py
Labels: approved, cncf-cla: yes, lgtm, needs-kind, release-note-none, size/S

#1452 update `deployment_crud.py` to include a `restart_deployment` method for typed client
  examples/deployment_crud.py
Labels: approved, cncf-cla: yes, kind/cleanup, kind/documentation, lgtm, release-note-none, size/L

#1418 Make job_crud example print the correct job status after job creation
  examples/job_crud.py
Labels: approved, cncf-cla: yes, lgtm, size/S

#1468 drop python 2 support
  .github/workflows/test.yaml
  .travis.yml
  examples/multiple_clusters.py
  examples/pick_kube_config_context.py
  examples/pod_config_list.py
  scripts/update-pycodestyle.sh
  setup.py
  tox.ini
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/M

#1472 replaced 2.7.12 with 3.9.1 version, as python 2 has come to end of life
  devel/release.md
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS
