Repository kubernetes-client/python, pull requests merged in 2021-06, with the labels that each got.

#1481 Skipping TestClient::test_portforward_raw due to flakiness
  kubernetes/e2e_test/test_client.py
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#1479 Reorder Changelog
  CHANGELOG.md
Labels: approved, cncf-cla: yes, kind/cleanup, kind/documentation, lgtm, release-note-none, size/M

#1480 Drop python 3.5
  .github/workflows/test.yaml
  .travis.yml
  setup.py
  tox.ini
Labels: approved, cncf-cla: yes, kind/cleanup, release-note-none, size/S

#1286 Move several workflows to GitHub Actions
  .github/workflows/e2e-master.yaml
  .github/workflows/e2e-release-11.0.yaml
  .github/workflows/e2e-release-12.0.yaml
  .github/workflows/e2e-release-17.0.yaml
  .github/workflows/e2e-release-18.0.yaml
  .github/workflows/kind-configs/cluster-1.15.yaml
  .github/workflows/kind-configs/cluster-1.16.yaml
  .github/workflows/kind-configs/cluster-1.17.yaml
  .github/workflows/kind-configs/cluster-1.18.yaml
  .travis.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/L

#1306 Update pyyaml from 3.1.2 to 5.4.1
  requirements.txt
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#1496 Release v18.20.0b1
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/e2e-master.yaml
  .github/workflows/e2e-release-11.0.yaml
  .github/workflows/e2e-release-12.0.yaml
  .github/workflows/e2e-release-17.0.yaml
  .github/workflows/e2e-release-18.0.yaml
  .github/workflows/kind-configs/cluster-1.15.yaml
  .github/workflows/kind-configs/cluster-1.16.yaml
  .github/workflows/kind-configs/cluster-1.17.yaml
  .github/workflows/kind-configs/cluster-1.18.yaml
  .github/workflows/test.yaml
  .travis.yml
  CHANGELOG.md
  README.md
  devel/release.md
  devel/submodules.md
  examples/cluster_scoped_custom_object.py
  examples/deployment_create.py
  examples/deployment_crud.py
  examples/dynamic-client/accept_header.py
  examples/dynamic-client/cluster_scoped_custom_resource.py
  examples/dynamic-client/configmap.py
  examples/dynamic-client/deployment_rolling_restart.py
  examples/dynamic-client/namespaced_custom_resource.py
  examples/dynamic-client/node.py
  examples/dynamic-client/replication_controller.py
  examples/dynamic-client/service.py
  examples/job_crud.py
  examples/multiple_clusters.py
  examples/namespaced_custom_object.py
  examples/node_labels.py
  examples/pick_kube_config_context.py
  examples/pod_config_list.py
  examples/remote_cluster.py
  kubernetes/README.md
  kubernetes/__init__.py
  kubernetes/client/__init__.py
  kubernetes/client/api_client.py
  kubernetes/client/configuration.py
  kubernetes/e2e_test/test_client.py
  requirements.txt
  scripts/apply-hotfixes.sh
  scripts/constants.py
  scripts/update-client.sh
  scripts/update-pycodestyle.sh
  scripts/update-submodule.sh
  scripts/util/changelog.sh
  scripts/util/common.sh
  setup.py
  tox.ini
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note-none, size/XXL

#1497 tolerate null sources on projected volumes
  kubernetes/client/models/v1_projected_volume_source.py
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/XS

#1499 Cherrypick README and CHANGLOG of v18.20.0b1 to master branch
  CHANGELOG.md
  README.md
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/S

#1498 update the hotfix script for tolerating null sources on projected volumes
  scripts/apply-hotfixes.sh
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/S
