Repository kubernetes-client/python, pull requests merged in 2021-08, with the labels that each got.

#1521 Require python3
  setup.py
Labels: lgtm, cncf-cla: yes, size/XS, kind/design, approved, release-note-none, kind/deprecation

#1520 Update release docs with more info
  devel/release.md
Labels: lgtm, cncf-cla: yes, size/M, kind/documentation, approved, release-note-none

#1527 Release 18.20.0
  CHANGELOG.md
  README.md
  kubernetes/README.md
  kubernetes/__init__.py
  kubernetes/client/__init__.py
  kubernetes/client/api_client.py
  kubernetes/client/configuration.py
  scripts/constants.py
  setup.py
Labels: kind/feature, lgtm, cncf-cla: yes, size/S, approved, release-note-none

#1528 Update changelog and readme in the master branch for v18 GA release
  CHANGELOG.md
  README.md
Labels: lgtm, cncf-cla: yes, size/S, approved, kind/cleanup, release-note-none
