Repository kubernetes-client/python, pull requests merged in 2022-10, with the labels that each got.

#1903 example added for create_from_dict
  examples/apply_from_dict.py
Labels: lgtm, cncf-cla: yes, size/S, kind/documentation, approved, release-note-none

#1899 Add e2e test for strategic merge patch
  kubernetes/e2e_test/test_client.py
Labels: kind/feature, lgtm, cncf-cla: yes, size/S, approved, release-note-none

#1910 added [back to top] button
  README.md
Labels: lgtm, cncf-cla: yes, size/XS, approved, release-note-none, needs-kind

#1913 Fixed scripts/rest_client_patch.diff, it is corrupt and cannot be applied
  scripts/rest_client_patch.diff
Labels: kind/bug, lgtm, cncf-cla: yes, size/XS, approved, release-note-none

#1919 Updated typo in example steps
  examples/node_labels.py
Labels: lgtm, cncf-cla: yes, size/XS, kind/documentation, approved, release-note-none

#1916 Add support for using oidc CA certificate file while refreshing token
  kubernetes/base/config/kube_config.py
  kubernetes/base/config/kube_config_test.py
Labels: kind/feature, lgtm, cncf-cla: yes, size/M, release-note, approved

#1922 mock.call_args.kwargs was added after python 3.7, switched to the old…
  kubernetes/base/config/exec_provider_test.py
Labels: kind/bug, lgtm, cncf-cla: yes, size/XS, approved, release-note-none

#1918 Automated release of 25.2.0a1 upstream release 25.0 1665521856
  CHANGELOG.md
  README.md
  kubernetes/README.md
  kubernetes/__init__.py
  kubernetes/base/config/exec_provider_test.py
  kubernetes/client/__init__.py
  kubernetes/client/api_client.py
  kubernetes/client/configuration.py
  scripts/constants.py
  setup.py
Labels: kind/bug, lgtm, cncf-cla: yes, size/S, approved, release-note-none

#1912 decoding a not safe url in load_kube_config
  kubernetes/base/config/kube_config.py
Labels: lgtm, cncf-cla: yes, size/XS, approved, release-note-none, needs-kind

#1926 Updated example description
  examples/rollout-daemonset.py
Labels: lgtm, cncf-cla: yes, size/XS, kind/documentation, approved, release-note-none

#1924 changelog and README for 1.25 alpha release
  CHANGELOG.md
  README.md
Labels: lgtm, cncf-cla: yes, size/XS, kind/documentation, approved, release-note-none

#1930 Automated release of 25.2.0b1 upstream release 25.0 1666284251
  CHANGELOG.md
  README.md
  examples/node_labels.py
  examples/rollout-daemonset.py
  kubernetes/README.md
  kubernetes/__init__.py
  kubernetes/base/config/kube_config.py
  kubernetes/base/config/kube_config_test.py
  kubernetes/client/__init__.py
  kubernetes/client/api_client.py
  kubernetes/client/configuration.py
  scripts/constants.py
  setup.py
Labels: kind/bug, lgtm, cncf-cla: yes, size/M, approved, release-note-none

#1931 Automated release of 25.3.0b1 upstream release 25.0 1666286324
  CHANGELOG.md
  README.md
  kubernetes/README.md
  kubernetes/__init__.py
  kubernetes/client/__init__.py
  kubernetes/client/api_client.py
  kubernetes/client/configuration.py
  scripts/constants.py
  setup.py
Labels: kind/bug, lgtm, cncf-cla: yes, size/S, approved, release-note-none

#1938 25.3 GA release changelog and README comptability matrix
  CHANGELOG.md
  README.md
Labels: lgtm, cncf-cla: yes, size/S, kind/documentation, approved, release-note-none
