Repository kubernetes-client/python, pull requests merged in 2022-06, with the labels that each got.

#1819 Automated release of 24.1.0a1 upstream release 24.0 1654552395
  CHANGELOG.md
  README.md
  kubernetes/README.md
  kubernetes/__init__.py
  kubernetes/client/__init__.py
  kubernetes/client/api_client.py
  kubernetes/client/configuration.py
  scripts/constants.py
  setup.py
Labels: kind/bug, lgtm, cncf-cla: yes, size/S, approved, release-note-none

#1820 v24.1.0a1 release
  CHANGELOG.md
  README.md
Labels: lgtm, cncf-cla: yes, size/XS, kind/documentation, approved, release-note-none

#1827 Automated release of 24.1.0b1 upstream release 24.0 1655138958
  CHANGELOG.md
  kubernetes/README.md
  kubernetes/__init__.py
  kubernetes/base/stream/ws_client.py
  kubernetes/client/__init__.py
  kubernetes/client/api_client.py
  kubernetes/client/configuration.py
  kubernetes/e2e_test/port_server.py
  kubernetes/e2e_test/test_client.py
  scripts/constants.py
  setup.py
Labels: kind/bug, lgtm, cncf-cla: yes, size/L, approved, release-note-none

#1828 update changelog with release notes from master branch
  CHANGELOG.md
Labels: kind/bug, lgtm, cncf-cla: yes, size/XS, approved, release-note-none

#1838 Automated release of 24.2.0 upstream release 24.0 1655852053
  .github/workflows/e2e-master.yaml
  .github/workflows/e2e-release-11.0.yaml
  .github/workflows/e2e-release-12.0.yaml
  .github/workflows/e2e-release-17.0.yaml
  .github/workflows/e2e-release-18.0.yaml
  .github/workflows/test.yaml
  CHANGELOG.md
  README.md
  kubernetes/README.md
  kubernetes/__init__.py
  kubernetes/client/__init__.py
  kubernetes/client/api_client.py
  kubernetes/client/configuration.py
  scripts/constants.py
  setup.py
Labels: kind/bug, lgtm, cncf-cla: yes, size/M, approved, release-note-none

#1839 GA release for 1.24.2
  CHANGELOG.md
  README.md
Labels: lgtm, cncf-cla: yes, size/S, kind/documentation, approved, release-note-none

#1843 example annotate deployment
  examples/annotate_deployment.py
Labels: lgtm, cncf-cla: yes, size/M, approved, release-note-none, needs-kind
