Repository kubernetes-client/python, pull requests merged in 2022-07, with the labels that each got.

#1848 Check availability of poll method before using
  kubernetes/base/stream/ws_client.py
Labels: kind/bug, lgtm, cncf-cla: yes, size/XS, approved, release-note-none, kind/regression

#1850 Fix DynamicClient.server_side_apply
  kubernetes/base/dynamic/test_client.py
  kubernetes/client/rest.py
  scripts/rest_client_patch.diff
Labels: kind/bug, lgtm, cncf-cla: yes, size/S, release-note, approved

#1833 Add interactive configuration to exec provider.
  kubernetes/base/config/exec_provider.py
Labels: kind/bug, lgtm, cncf-cla: yes, size/XS, approved, release-note-none

#1854 Add 'usedforsecurity=False' parameter to md5 call
  kubernetes/base/dynamic/discovery.py
Labels: kind/bug, lgtm, cncf-cla: yes, size/XS, approved, release-note-none

#1852 add a cronjob crud example
  examples/cronjob_crud.py
Labels: lgtm, cncf-cla: yes, size/L, kind/documentation, approved, release-note-none

#1860 Deploy docs as wiki
  .github/workflows/deploy-wiki.yaml
Labels: kind/feature, lgtm, cncf-cla: yes, size/M, kind/documentation, approved, release-note-none
