Repository kubernetes-client/python, pull requests merged in 2022-03, with the labels that each got.

#1717 add examples which mainly show a way to rollout statefulset and daemo…
  examples/rollout-daemonset.py
  examples/rollout-statefulset.py
Labels: lgtm, cncf-cla: yes, size/L, approved, release-note-none, needs-kind

#1749 fix: remove depriciated gitrepo volume type
  examples/notebooks/README.md
  examples/notebooks/docker/jupyter.yml
Labels: lgtm, cncf-cla: yes, size/M, approved, kind/cleanup, release-note-none

#1752 docs(examples): add example to utilize utils
  examples/apply_from_directory.py
  examples/apply_from_single_file.py
  examples/configmap-demo-pod.yml
  examples/yaml_dir/config_map.yml
  examples/yaml_dir/pod.yml
Labels: lgtm, cncf-cla: yes, size/L, approved, kind/cleanup, release-note-none

#1765 Fix typo: kubenetes -> kubernetes
  kubernetes/base/run_tox.sh
Labels: lgtm, cncf-cla: yes, size/XS, approved, release-note-none, needs-kind

#1738 fix issue when trying to build ResourceField with argument name 'self'
  kubernetes/base/dynamic/resource.py
  kubernetes/base/dynamic/test_client.py
Labels: lgtm, cncf-cla: yes, size/S, approved, release-note-none, needs-kind
