Repository kubernetes-client/python, pull requests merged in 2022-01, with the labels that each got.

#1670 Removed "Additional documentation" section.
  CHANGELOG.md
Labels: lgtm, cncf-cla: yes, size/S, kind/documentation, approved, release-note-none

#1677 Remove duplicate code in documentation
  kubernetes/README.md
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/cleanup, release-note-none

#1659 Updates to migrate from travis CI to GitHub Actions
  .travis.yml
  scripts/kube-init.sh
Labels: lgtm, cncf-cla: yes, size/L, approved, release-note-none, needs-kind

#1691 Automated release of 22.6.0a1 upstream release 22.0 1643658718
  CHANGELOG.md
  README.md
  kubernetes/README.md
  kubernetes/__init__.py
  kubernetes/client/__init__.py
  kubernetes/client/api_client.py
  kubernetes/client/configuration.py
  scripts/constants.py
  setup.py
Labels: kind/bug, lgtm, cncf-cla: yes, size/S, approved, release-note-none
