Repository kubernetes-client/python, pull requests merged in 2022-02, with the labels that each got.

#1683 feat: add create from directory support
  kubernetes/e2e_test/test_utils.py
  kubernetes/e2e_test/test_yaml/multi-resource/multi-resource-replication-controller.yaml
  kubernetes/e2e_test/test_yaml/multi-resource/multi-resource-service.yaml
  kubernetes/utils/__init__.py
  kubernetes/utils/create_from_yaml.py
Labels: kind/feature, lgtm, cncf-cla: yes, size/L, release-note, approved

#1692 removed docs and scripts around submodules. submodules are no longer
  devel/release.md
  devel/submodules.md
  scripts/update-submodule.sh
Labels: lgtm, cncf-cla: yes, size/L, kind/documentation, approved, release-note-none

#1695 Automated release of 22.6.0b1 upstream release 22.0 1644255027
  CHANGELOG.md
  devel/release.md
  devel/submodules.md
  kubernetes/README.md
  kubernetes/__init__.py
  kubernetes/client/__init__.py
  kubernetes/client/api_client.py
  kubernetes/client/configuration.py
  kubernetes/e2e_test/test_utils.py
  kubernetes/e2e_test/test_yaml/multi-resource/multi-resource-replication-controller.yaml
  kubernetes/e2e_test/test_yaml/multi-resource/multi-resource-service.yaml
  kubernetes/utils/__init__.py
  kubernetes/utils/create_from_yaml.py
  scripts/constants.py
  scripts/update-submodule.sh
  setup.py
Labels: kind/bug, lgtm, cncf-cla: yes, size/L, approved, release-note-none

#1697 Async fix for Dynamic Client
  kubernetes/base/dynamic/client.py
  kubernetes/base/dynamic/test_client.py
Labels: kind/bug, lgtm, cncf-cla: yes, size/L, release-note, approved

#1700 Generate and upload code coverage
  .github/workflows/test.yaml
  codecov.yml
  test-requirements.txt
  tox.ini
Labels: lgtm, cncf-cla: yes, size/M, kind/documentation, approved, kind/cleanup, release-note-none

#1707 update changelog with release notes from master branch for 1.22.6b1
  CHANGELOG.md
Labels: lgtm, cncf-cla: yes, size/XS, kind/documentation, approved, release-note-none

#1708 updated changelog and README for 1.22.6
  CHANGELOG.md
  README.md
Labels: lgtm, cncf-cla: yes, size/S, kind/documentation, approved, release-note-none

#1711 Automated release of 23.3.0a1 upstream release 23.0 1644900860
  CHANGELOG.md
  README.md
  kubernetes/README.md
  kubernetes/__init__.py
  kubernetes/client/__init__.py
  kubernetes/client/api_client.py
  kubernetes/client/configuration.py
  scripts/constants.py
  setup.py
Labels: kind/bug, lgtm, cncf-cla: yes, size/S, approved, release-note-none

#1714 updated readme and changelog for 1.23.3a1
  CHANGELOG.md
  README.md
Labels: lgtm, cncf-cla: yes, size/XS, kind/documentation, approved, release-note-none

#1720 Automated release of 23.3.0b1 upstream release 23.0 1645549885
  CHANGELOG.md
  README.md
  kubernetes/README.md
  kubernetes/__init__.py
  kubernetes/client/__init__.py
  kubernetes/client/api_client.py
  kubernetes/client/configuration.py
  scripts/constants.py
  setup.py
Labels: kind/bug, lgtm, cncf-cla: yes, size/S, approved, release-note-none

#1721 updated changelog and readme
  CHANGELOG.md
  README.md
Labels: lgtm, cncf-cla: yes, size/S, kind/documentation, approved, release-note-none

#1722 updated annoucement mail to dev@kubernetes.io
  devel/release.md
Labels: lgtm, cncf-cla: yes, size/XS, kind/documentation, approved, release-note-none

#1730 updated compatibility matrix for 1.23.3 GA
  CHANGELOG.md
  README.md
Labels: lgtm, cncf-cla: yes, size/S, kind/documentation, approved, release-note-none
