Repository kubernetes-client/python, pull requests merged in 2022-05, with the labels that each got.

#1788 add: README.md in doc/source
  doc/source/README.md
Labels: lgtm, cncf-cla: yes, size/L, kind/documentation, approved, release-note-none

#1795 Update changelog and readme in master branch
  CHANGELOG.md
  README.md
Labels: lgtm, cncf-cla: yes, size/S, approved, kind/cleanup, release-note-none

#1732 Support setting the _request_timeout parameter for the dynamic client
  kubernetes/base/dynamic/client.py
Labels: lgtm, cncf-cla: yes, size/XS, release-note, approved, needs-kind

#1781 Set cwd to None if empty string for ExecProvider
  kubernetes/base/config/exec_provider.py
Labels: kind/bug, lgtm, cncf-cla: yes, size/XS, approved, release-note-none
