Repository kubernetes-client/python, pull requests merged in 2022-08, with the labels that each got.

#1874 Remove duplicate
  kubernetes/README.md
Labels: lgtm, cncf-cla: yes, size/XS, kind/documentation, approved, release-note-none

#1871 fix issue #1782 Resolve load_kube_config TMP file issue
  kubernetes/base/config/kube_config.py
Labels: kind/bug, lgtm, cncf-cla: yes, size/XS, approved, release-note-none

#1804 Instead of mock, used unittest.mock
  kubernetes/base/config/exec_provider_test.py
  kubernetes/base/config/kube_config_test.py
  kubernetes/base/watch/watch_test.py
Labels: lgtm, cncf-cla: yes, size/XS, approved, release-note-none, needs-kind
