Repository kubernetes-client/python, pull requests merged in 2023-12, with the labels that each got.

#2166 cherry pick README and CHANGELOG for 1.29 alpha
  CHANGELOG.md
  README.md
Labels: lgtm, cncf-cla: yes, size/XS, kind/documentation, approved, release-note-none

#2165 Automated release of 29.0.0a1 upstream release 29.0 1702936304
  CHANGELOG.md
  README.md
  kubernetes/README.md
  kubernetes/__init__.py
  kubernetes/client/__init__.py
  kubernetes/client/api_client.py
  kubernetes/client/configuration.py
  scripts/constants.py
  setup.py
Labels: kind/bug, lgtm, cncf-cla: yes, size/S, approved, release-note-none

#2100 Fix UTF-8 failures in Watch
  kubernetes/base/watch/watch.py
  kubernetes/base/watch/watch_test.py
Labels: kind/bug, lgtm, cncf-cla: yes, size/L, release-note, approved
