Repository kubernetes-client/python, pull requests merged in 2023-01, with the labels that each got.

#1935 Fixed double module imports
  kubernetes/__init__.py
Labels: lgtm, cncf-cla: yes, size/S, approved, kind/cleanup, release-note-none

#1949 Improve the refreshing of tokens from inside the cluster
  kubernetes/base/config/incluster_config.py
Labels: lgtm, cncf-cla: yes, size/XS, approved, release-note-none, needs-kind

#1991 updated kind action version, kind version, and node image version.
  .github/workflows/e2e-master.yaml
  .github/workflows/kind-configs/cluster-1.25.yaml
Labels: kind/bug, lgtm, cncf-cla: yes, size/S, approved, release-note-none

#1993 Removed 3.6 python version
  .github/workflows/test.yaml
Labels: kind/bug, lgtm, cncf-cla: yes, size/XS, approved, release-note-none

#1994 Automated release of 26.1.0a1 upstream release 26.0 1674599031
  CHANGELOG.md
  README.md
  kubernetes/README.md
  kubernetes/__init__.py
  kubernetes/client/__init__.py
  kubernetes/client/api_client.py
  kubernetes/client/configuration.py
  scripts/constants.py
  setup.py
  tox.ini
Labels: kind/bug, lgtm, cncf-cla: yes, size/S, approved, release-note-none

#1997 Dynamic Client Request Timeout Example
  examples/dynamic-client/request_timeout.py
  examples/watch/timeout-settings.md
Labels: lgtm, cncf-cla: yes, size/M, kind/documentation, release-note, approved

#1980 doc: comment pod_exec.py for multiple containers
  examples/pod_exec.py
Labels: lgtm, cncf-cla: yes, size/XS, kind/documentation, approved, release-note-none

#1971 added newline at the end of code.
  examples/dynamic-client/accept_header.py
Labels: lgtm, cncf-cla: yes, size/XS, approved, release-note-none, needs-kind

#1996 update README and CHANGELOG
  .github/workflows/test.yaml
  CHANGELOG.md
  README.md
  tox.ini
Labels: kind/bug, lgtm, cncf-cla: yes, size/S, approved, release-note-none

#1976 Convert timeout to milliseconds when using poll method
  kubernetes/base/stream/ws_client.py
Labels: kind/bug, lgtm, cncf-cla: yes, size/XS, release-note, approved

#1902 Fix small misspelling error
  kubernetes/utils/quantity.py
Labels: lgtm, cncf-cla: yes, size/XS, approved, release-note-none, needs-kind

#2003 added 3.11 to the tests
  .github/workflows/test.yaml
Labels: kind/feature, lgtm, cncf-cla: yes, size/XS, approved, release-note-none

#2004 Automated release of 26.1.0b1 upstream release 26.0 1675142889
  .github/workflows/test.yaml
  CHANGELOG.md
  README.md
  examples/dynamic-client/accept_header.py
  examples/dynamic-client/request_timeout.py
  examples/pod_exec.py
  examples/watch/timeout-settings.md
  kubernetes/README.md
  kubernetes/__init__.py
  kubernetes/base/stream/ws_client.py
  kubernetes/client/__init__.py
  kubernetes/client/api_client.py
  kubernetes/client/configuration.py
  kubernetes/utils/quantity.py
  scripts/constants.py
  setup.py
Labels: kind/bug, lgtm, cncf-cla: yes, size/L, approved, release-note-none

#2007 added release 1.26 e2e
  .github/workflows/e2e-release-26.0.yaml
  .github/workflows/kind-configs/cluster-1.26.yaml
Labels: kind/feature, lgtm, cncf-cla: yes, size/M, approved, release-note-none
