Repository kubernetes-client/python, pull requests merged in 2023-02, with the labels that each got.

#2008 1.26.1 beta README and CHANGELOG
  CHANGELOG.md
  README.md
Labels: lgtm, cncf-cla: yes, size/S, kind/documentation, approved, release-note-none

#1886 Add to_dict method to ResourceField
  kubernetes/base/dynamic/resource.py
  kubernetes/base/dynamic/test_client.py
Labels: kind/feature, lgtm, cncf-cla: yes, size/S, release-note, approved

#1998 Fix typos
  doc/source/usage.rst
  examples/README.md
  examples/deployment_crud.py
  examples/dynamic-client/cluster_scoped_custom_resource.py
  examples/notebooks/create_pod.ipynb
  examples/notebooks/create_secret.ipynb
  examples/rollout-daemonset.py
  examples/rollout-statefulset.py
  kubernetes/base/config/kube_config.py
  kubernetes/base/dynamic/resource.py
  kubernetes/base/leaderelection/resourcelock/configmaplock.py
  kubernetes/base/stream/ws_client.py
  kubernetes/client/models/discovery_v1_endpoint_port.py
  kubernetes/docs/DiscoveryV1EndpointPort.md
  kubernetes/docs/V1PersistentVolumeClaimCondition.md
  kubernetes/docs/V1PodDisruptionBudgetStatus.md
  scripts/util/kube_changelog.sh
Labels: lgtm, cncf-cla: yes, size/M, kind/documentation, approved, release-note-none

#2012 changelog and readme
  CHANGELOG.md
  README.md
Labels: lgtm, cncf-cla: yes, size/S, kind/documentation, approved, release-note-none

#2018 Fix snapshot version to be compliant with PEP440.
  kubernetes/README.md
  kubernetes/__init__.py
  kubernetes/client/__init__.py
  kubernetes/client/api_client.py
  kubernetes/client/configuration.py
  scripts/constants.py
  scripts/release.sh
  setup.py
Labels: kind/bug, lgtm, cncf-cla: yes, size/S, kind/failing-test, approved, release-note-none

#2016 fix broken oauthlib dependency
  requirements.txt
Labels: kind/bug, lgtm, cncf-cla: yes, size/XS, approved, release-note-none

#2013 [doc] update Sphinx configuration
  .gitignore
  doc/.gitignore
  doc/Makefile
  doc/source/README.md
  doc/source/conf.py
  doc/source/kubernetes.client.apis.rst
  doc/source/kubernetes.client.models.rst
  doc/source/kubernetes.client.rst
  doc/source/kubernetes.config.rst
  doc/source/kubernetes.rst
  doc/source/kubernetes.test.rst
  doc/source/kubernetes.watch.rst
Labels: lgtm, cncf-cla: yes, size/XXL, kind/documentation, approved, release-note-none
