Repository kubernetes-client/python, pull requests merged in 2023-09, with the labels that each got.

#2120 Automated release of 28.1.0b1 upstream release 28.0 1694205668
  CHANGELOG.md
  README.md
  kubernetes/README.md
  kubernetes/__init__.py
  kubernetes/client/__init__.py
  kubernetes/client/api_client.py
  kubernetes/client/configuration.py
  scripts/constants.py
  setup.py
Labels: kind/bug, lgtm, cncf-cla: yes, size/S, approved, release-note-none

#2121 update changelog and readme for 1.28.1 beta release
  CHANGELOG.md
  README.md
Labels: lgtm, cncf-cla: yes, size/XS, kind/documentation, approved, release-note-none

#2122 chore: move yaml files to correct folder
  examples/deployment_create.py
  examples/yaml_dir/configmap-demo-pod.yml
  examples/yaml_dir/nginx-deployment.yaml
  examples/yaml_dir/pi-job.yaml
Labels: lgtm, cncf-cla: yes, size/XS, kind/design, approved, release-note-none

#2124 chore: use f-string in place of old-style formatted string
  examples/annotate_deployment.py
  examples/api_discovery.py
  examples/apply_from_directory.py
  examples/apply_from_single_file.py
  examples/cluster_scoped_custom_object.py
  examples/deployment_create.py
  examples/in_cluster_config.py
  examples/job_crud.py
  examples/multiple_clusters.py
  examples/node_labels.py
  examples/out_of_cluster_config.py
  examples/pick_kube_config_context.py
  examples/pod_config_list.py
  examples/pod_exec.py
  examples/pod_portforward.py
  examples/remote_cluster.py
Labels: lgtm, cncf-cla: yes, size/L, approved, kind/cleanup, release-note-none

#2126 Automated release of 28.1.0 upstream release 28.0 1694967840
  .github/workflows/deploy-wiki.yaml
  .github/workflows/e2e-master.yaml
  .github/workflows/e2e-release-11.0.yaml
  .github/workflows/e2e-release-12.0.yaml
  .github/workflows/e2e-release-17.0.yaml
  .github/workflows/e2e-release-18.0.yaml
  .github/workflows/e2e-release-26.0.yaml
  .github/workflows/test.yaml
  CHANGELOG.md
  README.md
  examples/annotate_deployment.py
  examples/api_discovery.py
  examples/apply_from_directory.py
  examples/apply_from_single_file.py
  examples/cluster_scoped_custom_object.py
  examples/deployment_create.py
  examples/in_cluster_config.py
  examples/job_crud.py
  examples/multiple_clusters.py
  examples/node_labels.py
  examples/out_of_cluster_config.py
  examples/pick_kube_config_context.py
  examples/pod_config_list.py
  examples/pod_exec.py
  examples/pod_portforward.py
  examples/remote_cluster.py
  examples/yaml_dir/configmap-demo-pod.yml
  examples/yaml_dir/nginx-deployment.yaml
  examples/yaml_dir/pi-job.yaml
  kubernetes/README.md
  kubernetes/__init__.py
  kubernetes/client/__init__.py
  kubernetes/client/api_client.py
  kubernetes/client/configuration.py
  scripts/constants.py
  setup.py
Labels: kind/bug, lgtm, cncf-cla: yes, size/L, approved, release-note-none

#2127 cherrypick changelog and README for 1.28 release
  CHANGELOG.md
  README.md
Labels: lgtm, cncf-cla: yes, size/S, kind/documentation, approved, release-note-none
