Repository kubernetes-client/python, pull requests merged in 2023-05, with the labels that each got.

#2055 use dl.k8s.io, not kubernetes-release bucket
  scripts/kube-init.sh
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/cleanup, release-note-none

#2050 Fix exception in ExecProvider when no console is attached.
  kubernetes/base/config/exec_provider.py
  kubernetes/base/config/exec_provider_test.py
Labels: kind/bug, lgtm, cncf-cla: yes, size/S, approved, release-note-none

#2059 fix: use dl.k8s.io, not kubernetes-release bucket
  scripts/kube-init.sh
Labels: lgtm, cncf-cla: yes, size/XS, priority/important-soon, approved, kind/cleanup, release-note-none

#2049 Prevent ConstructorError when parsing YAML containing '=' scalars
  kubernetes/utils/create_from_yaml.py
Labels: kind/bug, lgtm, cncf-cla: yes, size/XS, approved, release-note-none
