Repository kubernetes-client/python, pull requests merged in 2023-08, with the labels that each got.

#2105 Setting upper version bound for urllib3
  requirements.txt
Labels: kind/bug, lgtm, cncf-cla: yes, size/XS, release-note, approved

#2113 update changelog with release notes from master branch
  CHANGELOG.md
Labels: lgtm, cncf-cla: yes, size/S, kind/documentation, approved, release-note-none

#2114 Automated release of 28.1.0a1 upstream release 28.0 1693513885
  CHANGELOG.md
  README.md
  kubernetes/README.md
  kubernetes/__init__.py
  kubernetes/client/__init__.py
  kubernetes/client/api_client.py
  kubernetes/client/configuration.py
  scripts/constants.py
  setup.py
Labels: kind/bug, lgtm, cncf-cla: yes, size/S, approved, release-note-none

#2115 cherry-pick README and CHANGELOG changes
  CHANGELOG.md
  README.md
Labels: lgtm, cncf-cla: yes, size/XS, kind/documentation, approved, release-note-none
