Repository kubernetes-client/python, pull requests merged in 2023-06, with the labels that each got.

#2065 Automated release of 27.2.0a1 upstream release 27.0 1685937313
  CHANGELOG.md
  README.md
  kubernetes/README.md
  kubernetes/__init__.py
  kubernetes/client/__init__.py
  kubernetes/client/api_client.py
  kubernetes/client/configuration.py
  scripts/constants.py
  setup.py
Labels: kind/bug, lgtm, cncf-cla: yes, size/S, approved, release-note-none

#2066 README and CHANGELOG
  CHANGELOG.md
  README.md
Labels: lgtm, cncf-cla: yes, size/XS, kind/documentation, approved, release-note-none

#2022 Remove erroneous runtime dependence on setuptools
  setup.py
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/cleanup, release-note-none

#2073 Automated release of 27.2.0b1 upstream release 27.0 1686329657
  CHANGELOG.md
  README.md
  kubernetes/README.md
  kubernetes/__init__.py
  kubernetes/client/__init__.py
  kubernetes/client/api_client.py
  kubernetes/client/configuration.py
  scripts/constants.py
  setup.py
Labels: kind/bug, lgtm, cncf-cla: yes, size/S, approved, release-note-none

#2074 updated README and release.md
  README.md
  devel/release.md
Labels: lgtm, cncf-cla: yes, size/XS, kind/documentation, approved, release-note-none

#2071 Fix request_timeout example and doc
  examples/dynamic-client/request_timeout.py
  examples/watch/timeout-settings.md
Labels: lgtm, cncf-cla: yes, size/XS, kind/documentation, release-note, approved

#2078 updated compatibility matrix and maintenance status
  README.md
Labels: lgtm, cncf-cla: yes, size/XS, kind/documentation, approved, release-note-none
