Repository kubernetes-client/python, pull requests merged in 2024-09, with the labels that each got.

#2278 cherry pick CHANGELOG and README for 1.31.0b1
  CHANGELOG.md
  README.md
Labels: lgtm, cncf-cla: yes, size/XS, kind/documentation, approved, release-note-none

#2277 Automated release of 31.0.0b1 upstream release 31.0 1725647903
  CHANGELOG.md
  README.md
  kubernetes/README.md
  kubernetes/__init__.py
  kubernetes/base/config/kube_config_test.py
  kubernetes/client/__init__.py
  kubernetes/client/api_client.py
  kubernetes/client/configuration.py
  scripts/constants.py
  setup.py
Labels: kind/bug, lgtm, cncf-cla: yes, size/S, approved, release-note-none

#2252 Add ability to use server_side_apply to utils.create_from_yaml
  kubernetes/e2e_test/test_utils.py
  kubernetes/utils/create_from_yaml.py
Labels: kind/feature, lgtm, cncf-cla: yes, size/L, release-note, approved

#2281 Automated release of 31.0.0 upstream release 31.0 1726263540
  CHANGELOG.md
  README.md
  kubernetes/README.md
  kubernetes/__init__.py
  kubernetes/client/__init__.py
  kubernetes/client/api_client.py
  kubernetes/client/configuration.py
  scripts/constants.py
  setup.py
Labels: kind/bug, lgtm, cncf-cla: yes, size/M, approved, release-note-none

#2282 updated README and CHANGELOG
  CHANGELOG.md
  README.md
Labels: lgtm, cncf-cla: yes, size/S, kind/documentation, approved, release-note-none

#2285 Remove mock from test-requirements.txt
  test-requirements.txt
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/cleanup, release-note-none
