Repository kubernetes-client/python, pull requests merged in 2024-11, with the labels that each got.

#2303 Support providing cluster info to the exec provider
  kubernetes/base/config/exec_provider.py
  kubernetes/base/config/exec_provider_test.py
  kubernetes/base/config/kube_config.py
Labels: lgtm, cncf-cla: yes, size/M, release-note, approved, needs-kind

#2288 Remove py from test-requirements.txt
  test-requirements.txt
Labels: lgtm, cncf-cla: yes, size/XS, release-note, approved, needs-kind

#2157 Avoid shadowing important built-ins in the example code
  kubernetes/base/watch/watch.py
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/cleanup, release-note-none
