Repository kubernetes-client/python, pull requests merged in 2024-02, with the labels that each got.

#2189 remove ipaddress from requirements.txt
  requirements.txt
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/cleanup, release-note-none

#2153 remove deprecated IOError
  kubernetes/base/config/kube_config_test.py
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/cleanup, release-note-none

#2178 Replace deprecated assertEquals call
  kubernetes/base/config/kube_config_test.py
Labels: kind/bug, lgtm, cncf-cla: yes, size/XS, kind/failing-test, approved, release-note-none

#2187 Fix merging current-context in kube-configs
  kubernetes/base/config/kube_config.py
  kubernetes/base/config/kube_config_test.py
Labels: kind/bug, lgtm, cncf-cla: yes, size/M, release-note, approved

#1968 kube-config: add custom client configuration injection
  kubernetes/base/config/kube_config.py
Labels: kind/feature, lgtm, cncf-cla: yes, size/S, release-note, approved

#2194 Enable binary support for WSClient
  kubernetes/base/stream/stream.py
  kubernetes/base/stream/ws_client.py
  kubernetes/e2e_test/test_client.py
Labels: kind/feature, lgtm, cncf-cla: yes, size/M, release-note, approved
