Repository kubernetes-client/python, pull requests merged in 2024-01, with the labels that each got.

#2172 Automated release of 29.0.0b1 upstream release 29.0 1703785760
  .github/workflows/e2e-master.yaml
  .github/workflows/e2e-release-11.0.yaml
  .github/workflows/e2e-release-12.0.yaml
  .github/workflows/e2e-release-17.0.yaml
  .github/workflows/e2e-release-18.0.yaml
  .github/workflows/e2e-release-26.0.yaml
  .github/workflows/test.yaml
  CHANGELOG.md
  kubernetes/README.md
  kubernetes/__init__.py
  kubernetes/base/watch/watch.py
  kubernetes/base/watch/watch_test.py
  kubernetes/client/__init__.py
  kubernetes/client/api_client.py
  kubernetes/client/configuration.py
  scripts/constants.py
  setup.py
Labels: kind/bug, lgtm, cncf-cla: yes, size/L, approved, release-note-none

#2173 update changelog with release notes from master branch
  CHANGELOG.md
Labels: lgtm, cncf-cla: yes, size/XS, kind/documentation, approved, release-note-none

#2177 cherry pick CHANGELOG and README from 1.29.0 release
  CHANGELOG.md
  README.md
Labels: lgtm, cncf-cla: yes, size/S, kind/documentation, approved, release-note-none

#2175 Provides a patch to stop using urllib3 deprecated APIs until the upgrade to latest OpenAPI Generator (>6.4.0)
  scripts/rest_urllib_headers.diff
  scripts/update-client.sh
Labels: kind/bug, lgtm, cncf-cla: yes, size/S, release-note, approved, kind/cleanup
