Repository kubernetes-client/python, pull requests merged in 2025-01, with the labels that each got.

#2323 Automated release of 32.0.0b1 upstream release 32.0 1737065239
  .github/workflows/e2e-master.yaml
  .github/workflows/e2e-release-11.0.yaml
  .github/workflows/e2e-release-12.0.yaml
  .github/workflows/e2e-release-17.0.yaml
  .github/workflows/e2e-release-18.0.yaml
  .github/workflows/e2e-release-26.0.yaml
  CHANGELOG.md
  README.md
  kubernetes/README.md
  kubernetes/__init__.py
  kubernetes/client/__init__.py
  kubernetes/client/api_client.py
  kubernetes/client/configuration.py
  scripts/constants.py
  setup.py
Labels: kind/bug, lgtm, cncf-cla: yes, size/M, approved, release-note-none

#2324 release 1.32.0 beta
  CHANGELOG.md
  README.md
Labels: kind/bug, lgtm, cncf-cla: yes, size/S, approved, release-note-none

#2316 Close the Python sockets when the Websocket closes
  kubernetes/base/stream/ws_client.py
Labels: kind/bug, lgtm, cncf-cla: yes, size/XS, release-note, approved

#2331 Automated release of 32.0.0 upstream release 32.0 1737659562
  CHANGELOG.md
  README.md
  kubernetes/README.md
  kubernetes/__init__.py
  kubernetes/base/stream/ws_client.py
  kubernetes/client/__init__.py
  kubernetes/client/api_client.py
  kubernetes/client/configuration.py
  scripts/constants.py
  setup.py
Labels: kind/bug, lgtm, cncf-cla: yes, size/M, approved, release-note-none

#2332 1.32.0 GA release
  CHANGELOG.md
  README.md
Labels: lgtm, cncf-cla: yes, size/S, kind/documentation, approved, release-note-none

#2216 Adding utils.format_quantity
  kubernetes/e2e_test/test_utils.py
  kubernetes/utils/quantity.py
Labels: kind/feature, lgtm, cncf-cla: yes, size/L, release-note, approved

#2338 mark shell=False in ExecProvider for linux/darwin platforms
  kubernetes/base/config/exec_provider.py
Labels: kind/bug, lgtm, cncf-cla: yes, size/S, approved, release-note-none
