Repository kubernetes-client/python, pull requests merged in 2025-05, with the labels that each got.

#2254 add .readthedocs.yaml config file to fix docs pipeline
  .readthedocs.yaml
Labels: lgtm, cncf-cla: yes, size/M, kind/documentation, approved, release-note-none

#2400 Automated release of 33.1.0a1 upstream release 33.0 1748372943
  CHANGELOG.md
  README.md
  kubernetes/README.md
  kubernetes/__init__.py
  kubernetes/client/__init__.py
  kubernetes/client/api_client.py
  kubernetes/client/configuration.py
  scripts/constants.py
  setup.py
Labels: kind/bug, lgtm, cncf-cla: yes, size/S, approved, release-note-none

#2401 updated compatibility matrix and maintenance status
  README.md
Labels: lgtm, cncf-cla: yes, size/XS, kind/documentation, approved, release-note-none
