Repository kubernetes-client/python, pull requests merged in 2025-04, with the labels that each got.

#2383 Update README.md
  kubernetes/README.md
Labels: lgtm, cncf-cla: yes, size/XS, kind/documentation, approved, release-note-none

#2384 Add instructions for enabling debug logging in the Kubernetes Python
  README.md
Labels: lgtm, cncf-cla: yes, size/S, kind/documentation, release-note, approved

#2317 Add support for allowWatchBookmarks to the dynamic client
  examples/watch/watch_recovery.py
  kubernetes/base/dynamic/client.py
Labels: kind/feature, lgtm, cncf-cla: yes, size/M, release-note, approved
